version: "2.1"

services:
  mariadb:
    image: "mariadb:10.9.2"
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_DATABASE=mc
    volumes:
      - "mariadb_data:/var/lib/mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=maria --execute \"SHOW DATABASES;\""

  zookeeper:
    image: "docker.io/bitnami/zookeeper:3.8"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "docker.io/bitnami/kafka:3.2"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mc1:
    image: evilball/mc1:0.1.0
    ports:
      - "8081:8081"
    environment:
      - SPRING_FLYWAY_URL=jdbc:mariadb://mariadb:3306/mc
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/mc
      - MC_WEBSOCKET_HOST=mc2
      - MC_PERIOD=5
    depends_on:
      mariadb:
        condition: service_healthy
  mc2:
    image: evilball/mc2:0.1.0
    environment:
      - MC_WEBSOCKET_HOST=mc2
      - MC_KAFKA_HOST=kafka
    depends_on:
      - mc1
      - kafka
  mc3:
    image: evilball/mc3:0.1.0
    environment:
      - MC_KAFKA_HOST=kafka
      - MC_MC1_HOST=mc1
    depends_on:
      - mc2
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mariadb_data:
    driver: local